CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Countries" (
        "NameCountry" text NOT NULL,
        "Latitude" integer NOT NULL,
        "Longitude" integer NOT NULL,
        "Index" text NOT NULL,
        CONSTRAINT "PK_Countries" PRIMARY KEY ("NameCountry")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Customers" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Email" text NULL,
        "Age" integer NOT NULL,
        "PassportData" text NOT NULL,
        "Sex" text NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Providers" (
        "ProviderId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "NameCompany" text NOT NULL,
        "LicenceNumber" text NOT NULL,
        "PhoneNumber" text NOT NULL,
        "Email" character varying(40) NOT NULL,
        "CountresProvider" text NOT NULL,
        CONSTRAINT "PK_Providers" PRIMARY KEY ("ProviderId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "RequestUser" (
        "Login" character varying(40) NOT NULL,
        "Role" text NOT NULL,
        "Password" text NOT NULL,
        CONSTRAINT "PK_RequestUser" PRIMARY KEY ("Login")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "User" (
        "Login" character varying(40) NOT NULL,
        "Role" text NOT NULL,
        "Password" text NOT NULL,
        "LockoutEnable" boolean NOT NULL,
        CONSTRAINT "PK_User" PRIMARY KEY ("Login")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Cargos" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Height" integer NOT NULL,
        "Width" integer NOT NULL,
        "Depth" integer NOT NULL,
        "Weight" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        CONSTRAINT "PK_Cargos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cargos_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Planes" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "IdProvider" integer NOT NULL,
        "NamePlane" text NULL,
        "ModelPlane" text NULL,
        "Height" integer NOT NULL,
        "Width" integer NOT NULL,
        depth integer NOT NULL,
        "CapacityWeight" integer NOT NULL,
        CONSTRAINT "PK_Planes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Planes_Providers_IdProvider" FOREIGN KEY ("IdProvider") REFERENCES "Providers" ("ProviderId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "RequestDeliveries" (
        "IdRequest" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ProviderId" integer NOT NULL,
        "CargoId" integer NOT NULL,
        "CountryIdTo" text NULL,
        "CountryIdFrom" text NOT NULL,
        "DateDeparture" timestamp without time zone NOT NULL,
        "DateDelivery" timestamp without time zone NOT NULL,
        "StatusRequest" boolean NOT NULL,
        "CastDelivery" double precision NOT NULL,
        CONSTRAINT "PK_RequestDeliveries" PRIMARY KEY ("IdRequest"),
        CONSTRAINT "FK_RequestDeliveries_Cargos_CargoId" FOREIGN KEY ("CargoId") REFERENCES "Cargos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RequestDeliveries_Countries_CountryIdFrom" FOREIGN KEY ("CountryIdFrom") REFERENCES "Countries" ("NameCountry") ON DELETE CASCADE,
        CONSTRAINT "FK_RequestDeliveries_Countries_CountryIdTo" FOREIGN KEY ("CountryIdTo") REFERENCES "Countries" ("NameCountry") ON DELETE RESTRICT,
        CONSTRAINT "FK_RequestDeliveries_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RequestDeliveries_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("ProviderId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE TABLE "Orders" (
        "OrderId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ProviderId" integer NOT NULL,
        "CargoId" integer NOT NULL,
        "PlaneId" integer NOT NULL,
        "CountryIdTo" text NOT NULL,
        "CountryIdFrom" text NOT NULL,
        "DateDeparture" timestamp without time zone NOT NULL,
        "DateDelivery" timestamp without time zone NOT NULL,
        "Status" text NULL,
        "CastDelivery" double precision NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_Orders_Cargos_CargoId" FOREIGN KEY ("CargoId") REFERENCES "Cargos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Countries_CountryIdFrom" FOREIGN KEY ("CountryIdFrom") REFERENCES "Countries" ("NameCountry") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Countries_CountryIdTo" FOREIGN KEY ("CountryIdTo") REFERENCES "Countries" ("NameCountry") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Planes_PlaneId" FOREIGN KEY ("PlaneId") REFERENCES "Planes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("ProviderId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Cargos_CustomerId" ON "Cargos" ("CustomerId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_CargoId" ON "Orders" ("CargoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_CountryIdFrom" ON "Orders" ("CountryIdFrom");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_CountryIdTo" ON "Orders" ("CountryIdTo");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_PlaneId" ON "Orders" ("PlaneId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Orders_ProviderId" ON "Orders" ("ProviderId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_Planes_IdProvider" ON "Planes" ("IdProvider");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_RequestDeliveries_CargoId" ON "RequestDeliveries" ("CargoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_RequestDeliveries_CountryIdFrom" ON "RequestDeliveries" ("CountryIdFrom");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_RequestDeliveries_CountryIdTo" ON "RequestDeliveries" ("CountryIdTo");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_RequestDeliveries_CustomerId" ON "RequestDeliveries" ("CustomerId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    CREATE INDEX "IX_RequestDeliveries_ProviderId" ON "RequestDeliveries" ("ProviderId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201207184804_qw') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201207184804_qw', '5.0.0');
    END IF;
END $$;
COMMIT;

